# Trackpad (IQS7211E) module configuration
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_IQS7211E=y

# Scroller tuning (optional)
# CONFIG_IQS7211E_TAP_EDGE_MARGIN_PERMILLE=80
# CONFIG_IQS7211E_SCROLLER_INERTIA=y
# CONFIG_IQS7211E_SCROLLER_INERTIA_DECAY_PERMILLE=920
