#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Debug logging (一時的に有効化、原因特定後に削除すること) -------------------
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_ZMK_LOG_LEVEL_DBG=y